### ISSUE TITLE
Improve GUI

### ISSUE THREAD

**Issue by ashishpapanai** [ashishpapanai/chessJS#3]
The current GUI of Engine is very minimalistic and simple, Contributors to this issue are supposed to follow the following task list, Contributions other than the mentioned tasks are always welcome.  Details about the codebase are mentioned in the Daily Progress Report document, Any extra details can be mentioned in the comments of this issue. 

- [x] Header with the Name of Engine and a tab to About Us section of the website

- [x] Footer Comprising details about copyright and Terms and Conditions as mentioned in the license. 

- [x] Colourful and Creative background to enhance the UI of the website. 

- [x] Change the font used on the website.

- [x] Improved about us page with subtle background and font.

**Comment by fatmab2809** [comment]
Hi, I would like to contribute to this issue for SWOC.

**Comment by fatmab2809** [comment]
I am planning to add Bootstrap framework, change font to Andika New Basic or Montserrat, change background image and add navigation bar that is provided by Bootstrap

**Comment by ashishpapanai** [comment]
> Hi, I would like to contribute to this issue for SWOC.

Please mention your contribution ideas in the project i.e. chessjs channel on slack

> I am planning to add Bootstrap framework, change the font to Andika New Basic or Montserrat, change the background image and add navigation bar that is provided by Bootstrap.

This sounds great.

**Comment by harikishantk** [comment]
I am SWOC 2021 participant and can I make a contribution to it? Kindly assign me. Thank you

**Comment by ashishpapanai** [comment]
@harikishantk you can start working on it.

**Comment by ashishpapanai** [comment]
Opened the issue to get better approaches and for fair participation of participants in SWOC.
