### ISSUE TITLE
Improve the responsiveness of the Website for users running it on non-standard devices

### ISSUE THREAD

**Issue by ashishpapanai** [ashishpapanai/chessJS#54]
## Currently, we are displaying a message that we prefer the user to use either a laptop or a pc with a certain resolution for best experience but that ruins the whole purpose of web and internet. 

We don't have a sure shot solution to this problem, Any participant with Good command over JQuery and responsiveness can take up this issue and come up with a solution or any resolutions/ follow up so that we can take up the suggestion and start working on it.

**Comment by somesh526** [comment]
Hello, @ashishpapanai I want to work on this issue under swoc2021, In the next 24-48 hours, I will share my idea with you. thank you
