### ISSUE TITLE
Improving the About Us Section of the website. 

### ISSUE THREAD

**Issue by ashishpapanai** [ashishpapanai/chessJS#55]
Link to the about us page. [About Us](https://chessjs.tech/about.html)
The about us page is having a clean and subtle design but doesn't look connected to the Main vibe of the project. Contributors to this issue are expected to make it much more lively and related to chess and the main idea of the page. 
The expected changes are: 

- [ ] Making the theme uniform and like the Home page of the website. 
- [ ] Improving the font and adding a background image / color as per the theme of the website. 
- [ ] Adding rules of chess to the about us page by using this pdf [Rules](https://www.fide.com/FIDE/handbook/LawsOfChess.pdf) a new page can be created as per the needs of the length of rules.
- [ ]  Adding the menu of the home page to the about page as well.

**Comment by Priyaraj17** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by ashishpapanai** [comment]
Hello@Priyaraj17,
The issues aren't assigned You work on it and send a pr if it fulfils the requirements it will be merged. You PRs will be scored even if they aren't merged.

**Comment by Priyaraj17** [comment]
Okay thank you.
