### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by Sloth-Panda** [ashishpapanai/chessJS#70]
The readme does not look so nice so can be improved by adding gifs and making orientation of things proper

**Comment by ashishpapanai** [comment]
You can work on the issue except for the part of the gifs.

**Comment by Sloth-Panda** [comment]
okay so you dont want gifs added right

**Comment by ashishpapanai** [comment]
Yes. @Sloth-Panda if this issue is related to SWOC 21, We can have a conversation in slack with all details about the fixes.

**Comment by ashishpapanai** [comment]
Closed due to inactivity.
