### ISSUE TITLE
Remove outline from the buttons and add hover effects instead

### ISSUE THREAD

**Issue by Abhijay007** [ashishpapanai/chessJS#79]
**Is your feature request related to a problem? Please describe.**

when the user clicks on the button then the button gets cover with an outline which looks not that great. we can add a hover effect to the button instead which improves UI and it also improves user experience

**Describe the solution you'd like**

CSS changes required

**Additional context**
screenshots:

![2021-01-14 (2)](https://user-images.githubusercontent.com/64387054/104594563-56b9ce00-5697-11eb-80f9-b750652b8237.png)

**Comment by ashishpapanai** [comment]
You can work on it @Abhijay007

**Comment by Abhijay007** [comment]
> You can work on it @Abhijay007

I think you need mentors permission for this 
but from my side YES!! you can work on this

**Comment by ashishpapanai** [comment]
Closed due to inactivity.
